name-template: 'Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ New Features'
    labels:
      - feature
  - title: 'ğŸ› Bug Fixes'
    labels:
      - bug
  - title: 'ğŸ§¹ Maintenance'
    labels:
      - maintenance
  - title: 'ğŸ—‚ï¸ Closed Issues'
    labels:
      - closed-issue  # Label issues with `closed-issue` to include in release notes

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## What's Changed
  $CHANGES

  ## Closed Issues
  $ISSUES
